# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebook/convolutions.ipynb.

# %% auto #0
__all__ = [
    "rng",
    "DEFAULT_KERNEL_SIZE",
    "DEFAULT_STRIDE",
    "DEFAULT_PADDING",
    "BYTES_PER_FLOAT32",
    "KB_TO_BYTES",
    "MB_TO_BYTES",
    "validate_4d_input",
    "Conv2dBackward",
    "Conv2d",
    "MaxPool2dBackward",
    "MaxPool2d",
    "AvgPool2dBackward",
    "AvgPool2d",
    "BatchNorm2d",
    "SimpleCNN",
]

import numpy as np

rng = np.random.default_rng(7)
import time

from tinytorch.foundation.tensor import Tensor
from tinytorch.foundation.activations import ReLU
from tinytorch.foundation.layers import Linear

# Enable autograd for gradient tracking (required for BatchNorm2d learnable parameters)
from tinytorch.foundation.autograd import enable_autograd, Function, ReLUBackward

enable_autograd()

# Constants for convolution defaults
DEFAULT_KERNEL_SIZE = 3  # Default kernel size for convolutions
DEFAULT_STRIDE = 1  # Default stride for convolutions
DEFAULT_PADDING = 0  # Default padding for convolutions

# Constants for memory calculations
BYTES_PER_FLOAT32 = 4  # Standard float32 size in bytes
KB_TO_BYTES = 1024  # Kilobytes to bytes conversion
MB_TO_BYTES = 1024 * 1024  # Megabytes to bytes conversion


def validate_4d_input(x, layer_name):
    """
    Validate that input tensor is 4D (batch, channels, height, width).
    """
    if len(x.shape) == 4:
        return  # Valid input

    if len(x.shape) == 3:
        raise ValueError(
            f"{layer_name} expected 4D input (batch, channels, height, width), got 3D: {x.shape}\n"
            f"  Missing batch dimension\n"
            f"  {layer_name} processes batches of images, not single images\n"
            f"  Add batch dim: x.reshape(1, {x.shape[0]}, {x.shape[1]}, {x.shape[2]})"
        )
    elif len(x.shape) == 2:
        raise ValueError(
            f"{layer_name} expected 4D input (batch, channels, height, width), got 2D: {x.shape}\n"
            f"  Got a matrix, expected an image tensor\n"
            f"  {layer_name} needs spatial dimensions (height, width) plus batch and channels\n"
            f"  If this is a flattened image, reshape it: x.reshape(1, channels, height, width)"
        )
    else:
        raise ValueError(
            f"{layer_name} expected 4D input (batch, channels, height, width), got {len(x.shape)}D: {x.shape}\n"
            f"  Wrong number of dimensions\n"
            f"  {layer_name} expects: (batch_size, channels, height, width)\n"
            f"  Reshape your input to 4D with the correct dimensions"
        )


class Conv2dBackward(Function):
    """Gradient computation for 2D convolution"""

    def __init__(self, x, weight, bias, stride, padding, kernel_size):
        # Register all tensors that need gradient with autograd
        if bias is not None:
            super().__init__(x, weight, bias)
        else:
            super().__init__(x, weight)
        self.x = x
        self.weight = weight
        self.bias = bias
        self.stride = stride
        self.padding = padding
        self.kernel_size = kernel_size

    def apply(self, grad_output):
        """Compute gradients for convolution inputs and parameters"""

        batch_size, out_channels, out_height, out_width = grad_output.shape
        _, in_channels, in_height, in_width = self.x.shape
        kernel_h, kernel_w = self.kernel_size

        # Apply padding to inputs if needed (for gradients computation)
        if self.padding > 0:
            padded_input = np.pad(
                self.x.data,
                (0, 0),
                (0, 0),
                (self.padding, self.padding),
                (self.padding, self.padding),
                mode="constant",
                constant_values=0,
            )
        else:
            padded_input = self.x.data

        # Initialize gradients
        grad_input_padded = np.zeros_like(padded_input)
        grad_weight = np.zeros_like(self.weight.data)
        grad_bias = None if self.bias is None else np.zeros_like(self.bias.data)

        # Compute gradients using explicit loops
        for b in range(batch_size):
            for out_ch in range(out_channels):
                for out_h in range(out_height):
                    for out_w in range(out_width):
                        in_h_start = out_h * self.stride
                        in_w_start = out_w * self.stride

                        # Gradient value flowing back to this position
                        grad_val = grad_output[b, out_ch, out_h, out_w]

                        for k_h in range(kernel_h):
                            for k_w in range(kernel_w):
                                for in_ch in range(in_channels):
                                    # Input positions
                                    in_h = in_h_start + k_h
                                    in_w = in_w_start + k_w

                                    # Gradient w.r.t weight
                                    grad_weight[out_ch, in_ch, k_h, k_w] += (
                                        grad_val * padded_input[b, in_ch, in_h, in_w]
                                    )

                                    # Gradient w.r.t input
                                    grad_input_padded[b, in_ch, in_h, in_w] += (
                                        grad_val
                                        * self.weight.data[out_ch, in_ch, k_h, k_w]
                                    )
        if grad_bias is not None:
            for out_ch in range(out_channels):
                grad_bias[out_ch] = grad_output[:, out_ch, :, :].sum()

        # Remove padding from input gradient
        if self.padding > 0:
            grad_input = grad_input_padded[
                :, :, self.padding : -self.padding, self.padding : -self.padding
            ]
        else:
            grad_input = grad_input_padded

        if self.bias is None:
            return grad_input, grad_weight
        else:
            return grad_input, grad_weight, grad_bias


class Conv2d:
    """2D convolution layer for spatial features extraction."""

    def __init__(
        self, in_channels, out_channels, kernel_size, stride=1, padding=0, bias=True
    ):

        self.in_channels = in_channels
        self.out_channels = out_channels

        # Handle kernel size as int or tuple
        if isinstance(kernel_size, int):
            self.kernel_size = (kernel_size, kernel_size)
        else:
            self.kernel_size = kernel_size

        self.stride = stride
        self.padding = padding

        # He initialization for ReLU networks
        kernel_h, kernel_w = self.kernel_size
        fan_in = kernel_h * kernel_w * in_channels
        std = np.sqrt(2.0 / fan_in)

        self.weight = Tensor(
            rng.normal(0, std, (out_channels, in_channels, kernel_h, kernel_w)),
            requires_grad=True,
        )

        # Bias initialization
        if bias:
            self.bias = Tensor(np.zeros(out_channels), requires_grad=True)
        else:
            self.bias = None

    def _compute_output_shape(self, in_h, in_w):
        """Calculate output spatial dimensions for convolution"""
        kernel_h, kernel_w = self.kernel_size
        out_w = (in_w + 2 * self.padding - kernel_w) // self.stride + 1
        out_h = (in_h + 2 * self.padding - kernel_h) // self.stride + 1

        return out_h, out_w

    def _apply_padding(self, x_data):
        """Zero-pad the spatial input dimensions"""

        if self.padding > 0:
            return np.pad(
                x_data,
                (
                    (0, 0),
                    (0, 0),
                    (self.padding, self.padding),
                    (self.padding, self.padding),
                ),
                mode="constant",
                constant_values=0,
            )
        else:
            return x_data

    def _convolve_loops(self, padded, batch_size, out_h, out_w):
        """sliding window dot products over inputs."""

        out_channels = self.out_channels
        in_channels = self.in_channels
        kernel_h, kernel_w = self.kernel_size

        output = np.zeros((batch_size, out_channels, out_h, out_w))

        for b in range(batch_size):
            for out_c in range(self.out_channels):
                for oh in range(out_h):
                    for ow in range(out_w):
                        in_h_start = oh * self.stride
                        in_w_start = ow * self.stride

                        conv_sum = 0.0
                        for k_h in range(kernel_h):
                            for k_w in range(kernel_w):
                                for in_c in range(in_channels):
                                    in_h = in_h_start + k_h
                                    in_w = in_w_start + k_w
                                    conv_sum += (
                                        self.weight.data[out_c, in_c, k_h, k_w]
                                        * padded[b, in_c, in_h, in_w]
                                    )
                        output[b, out_c, oh, ow] = conv_sum

        return output

    def forward(self, x):
        """Forward pass through con2d layer"""
        # Validate inputs
        validate_4d_input(x, "Conv2d")

        batch_size, in_channels, in_height, in_width = x.shape

        # Compute output dimensions
        out_height, out_width = self._compute_output_shape(in_height, in_width)

        # Apply padding
        padded_input = self._apply_padding(x.data)

        # Run convolution loop
        output = self._convolve_loops(padded_input, batch_size, out_height, out_width)

        # Add bias if present
        if self.bias is not None:
            for out_ch in range(self.out_channels):
                output[:, out_ch, :, :] += self.bias.data[out_ch]

        result = Tensor(
            output, requires_grad=(x.requires_grad or self.weight.requires_grad)
        )

        if result.requires_grad:
            result._grad_fn = Conv2dBackward(
                x, self.weight, self.bias, self.stride, self.padding, self.kernel_size
            )
        return result

    def parameters(self):
        """Return trainable parameters."""
        params = [self.weight]
        if self.bias is not None:
            params.append(self.bias)
        return params

    def __call__(self, x):
        """Enable model(x) syntax."""
        return self.forward(x)


class MaxPool2dBackward(Function):
    """Gradien t computation for 2D max pooling"""

    def __init__(self, x, output_shape, kernel_size, stride, padding):
        super().__init__(x)
        self.x = x
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.output_shape = output_shape
        # Store max positions for gradient routing
        self.max_positions = {}

    def apply(self, grad_output):
        batch_size, channels, in_height, in_width = self.x.shape
        _, _, out_height, out_width = self.output_shape
        kernel_h, kernel_w = self.kernel_size

        if self.padding > 0:
            padded_input = np.pad(
                self.x.data,
                (0, 0),
                (0, 0),
                (self.padding, self.padding),
                (self.padding, self.padding),
                mode="constant",
                constant_values=-np.inf,
            )
            grad_padded_input = np.zeros_like(padded_input)
        else:
            padded_input = self.x.data
            grad_padded_input = np.zeros_like(padded_input)

        for b in range(batch_size):
            for ch in range(channels):
                for out_h in range(out_height):
                    for out_w in range(out_width):
                        in_h_start = out_h * self.stride
                        in_w_start = out_w * self.stride

                        max_val = -np.inf
                        max_h, max_w = 0, 0
                        for k_h in range(kernel_h):
                            for k_w in range(kernel_w):
                                in_h = in_h_start + k_h
                                in_w = in_w_start + k_w
                                val = padded_input[b, ch, in_h, in_w]

                                if val > max_val:
                                    max_val = val
                                    max_h, max_w = in_h, in_w

                        # Route gradient to max position
                        grad_padded_input[b, ch, max_h, max_w] += grad_output[
                            b, ch, out_h, out_w
                        ]

        # Rmoving padding data
        if self.padding > 0:
            grad_input = grad_padded_input[
                :, :, self.padding : -self.padding, : self.padding : -self.padding
            ]
        else:
            grad_input = grad_padded_input

        return (grad_input,)


class MaxPool2d:
    """
    2D Max Pooling layer for spatial dimension reduction.
    """

    def __init__(self, kernel_size, stride=None, padding=0):
        """
        Initialize MaxPool2d layer.
        """

        # Handle kernel_size as int or tuple
        if isinstance(kernel_size, int):
            self.kernel_size = (kernel_size, kernel_size)
        else:
            self.kernel_size = kernel_size

        # Default stride equals kernel_size (non-overlapping)
        if stride is None:
            self.stride = self.kernel_size[0]
        else:
            self.stride = stride

        self.padding = padding

    def _compute_pool_output_shape(self, in_h, in_w):
        """
        Calculate output spatial dimensions for pooling.
        """

        kernel_h, kernel_w = self.kernel_size
        out_height = (in_h + 2 * self.padding - kernel_h) // self.stride + 1
        out_width = (in_w + 2 * self.padding - kernel_w) // self.stride + 1
        return out_height, out_width

    def _maxpool_loops(self, padded, batch_size, channels, out_h, out_w):
        """
        The core max pooling: find maximum value in each window.
        """

        kernel_h, kernel_w = self.kernel_size
        output = np.zeros((batch_size, channels, out_h, out_w))

        for b in range(batch_size):
            for c in range(channels):
                for oh in range(out_h):
                    for ow in range(out_w):
                        in_h_start = oh * self.stride
                        in_w_start = ow * self.stride

                        max_val = -np.inf
                        for k_h in range(kernel_h):
                            for k_w in range(kernel_w):
                                input_val = padded[
                                    b, c, in_h_start + k_h, in_w_start + k_w
                                ]
                                max_val = max(max_val, input_val)

                        output[b, c, oh, ow] = max_val

        return output

    def forward(self, x):
        """
        Forward pass through MaxPool2d layer.
        """

        # Step 1: Validate input
        validate_4d_input(x, "MaxPool2d")

        batch_size, channels, in_height, in_width = x.shape

        # Step 2: Compute output dimensions
        out_height, out_width = self._compute_pool_output_shape(in_height, in_width)

        # Step 3: Apply padding (use -inf for max pooling so padded values are never selected)
        if self.padding > 0:
            padded_input = np.pad(
                x.data,
                (
                    (0, 0),
                    (0, 0),
                    (self.padding, self.padding),
                    (self.padding, self.padding),
                ),
                mode="constant",
                constant_values=-np.inf,
            )
        else:
            padded_input = x.data

        # Step 4: Run max pooling loops
        output = self._maxpool_loops(
            padded_input, batch_size, channels, out_height, out_width
        )

        # Step 5: Return Tensor with gradient tracking
        result = Tensor(output, requires_grad=x.requires_grad)

        if result.requires_grad:
            result._grad_fn = MaxPool2dBackward(
                x, result.shape, self.kernel_size, self.stride, self.padding
            )

        return result

    def parameters(self):
        """Return empty list (pooling has no parameters)."""
        return []

    def __call__(self, x):
        """Enable model(x) syntax."""
        return self.forward(x)


class AvgPool2dBackward(Function):
    """
    Gradient computation for 2D average pooling.
    """

    def __init__(self, x, output_shape, kernel_size, stride, padding):
        super().__init__(x)
        self.x = x
        self.output_shape = output_shape
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding

    def apply(self, grad_output):
        """
        Distribute each output gradient equally across its pooling window.
        """
        batch_size, channels, in_height, in_width = self.x.shape
        _, _, out_height, out_width = self.output_shape
        kernel_h, kernel_w = self.kernel_size
        kernel_area = kernel_h * kernel_w

        # Average pooling pads with zeros, so the gradient buffer is padded with
        # zeros too (matching the forward pass).
        if self.padding > 0:
            grad_input_padded = np.zeros(
                (
                    batch_size,
                    channels,
                    in_height + 2 * self.padding,
                    in_width + 2 * self.padding,
                )
            )
        else:
            grad_input_padded = np.zeros_like(self.x.data)

        # Spread each output gradient equally over its window, accumulating overlaps.
        for b in range(batch_size):
            for c in range(channels):
                for out_h in range(out_height):
                    for out_w in range(out_width):
                        in_h_start = out_h * self.stride
                        in_w_start = out_w * self.stride
                        share = grad_output[b, c, out_h, out_w] / kernel_area
                        for k_h in range(kernel_h):
                            for k_w in range(kernel_w):
                                grad_input_padded[
                                    b, c, in_h_start + k_h, in_w_start + k_w
                                ] += share

        # Remove padding
        if self.padding > 0:
            grad_input = grad_input_padded[
                :, :, self.padding : -self.padding, self.padding : -self.padding
            ]
        else:
            grad_input = grad_input_padded

        # Return as tuple (following Function protocol)
        return (grad_input,)


class AvgPool2d:
    """
    2D Average Pooling layer for spatial dimension reduction.
    """

    def __init__(self, kernel_size, stride=None, padding=0):
        """
        Initialize AvgPool2d layer.
        """

        # Handle kernel_size as int or tuple
        if isinstance(kernel_size, int):
            self.kernel_size = (kernel_size, kernel_size)
        else:
            self.kernel_size = kernel_size

        # Default stride equals kernel_size (non-overlapping)
        if stride is None:
            self.stride = self.kernel_size[0]
        else:
            self.stride = stride

        self.padding = padding

    def _compute_pool_output_shape(self, in_h, in_w):
        """
        Calculate output spatial dimensions for pooling.
        """

        kernel_h, kernel_w = self.kernel_size
        out_height = (in_h + 2 * self.padding - kernel_h) // self.stride + 1
        out_width = (in_w + 2 * self.padding - kernel_w) // self.stride + 1
        return out_height, out_width

    def _avgpool_loops(self, padded, batch_size, channels, out_h, out_w):
        """
        The core average pooling: compute mean of each window.
        """

        kernel_h, kernel_w = self.kernel_size
        output = np.zeros((batch_size, channels, out_h, out_w))

        for b in range(batch_size):
            for c in range(channels):
                for oh in range(out_h):
                    for ow in range(out_w):
                        in_h_start = oh * self.stride
                        in_w_start = ow * self.stride

                        window_sum = 0.0
                        for k_h in range(kernel_h):
                            for k_w in range(kernel_w):
                                input_val = padded[
                                    b, c, in_h_start + k_h, in_w_start + k_w
                                ]
                                window_sum += input_val

                        output[b, c, oh, ow] = window_sum / (kernel_h * kernel_w)

        return output

    def forward(self, x):
        """
        Forward pass through AvgPool2d layer.
        """

        # Step 1: Validate input
        validate_4d_input(x, "AvgPool2d")

        batch_size, channels, in_height, in_width = x.shape

        # Step 2: Compute output dimensions
        out_height, out_width = self._compute_pool_output_shape(in_height, in_width)

        # Step 3: Apply padding (use zeros for average pooling)
        if self.padding > 0:
            padded_input = np.pad(
                x.data,
                (
                    (0, 0),
                    (0, 0),
                    (self.padding, self.padding),
                    (self.padding, self.padding),
                ),
                mode="constant",
                constant_values=0,
            )
        else:
            padded_input = x.data

        # Step 4: Run average pooling loops
        output = self._avgpool_loops(
            padded_input, batch_size, channels, out_height, out_width
        )

        # Step 5: Return Tensor with gradient tracking
        result = Tensor(output, requires_grad=x.requires_grad)

        if result.requires_grad:
            result._grad_fn = AvgPool2dBackward(
                x, result.shape, self.kernel_size, self.stride, self.padding
            )

        return result

    def parameters(self):
        """Return empty list (pooling has no parameters)."""
        return []

    def __call__(self, x):
        """Enable model(x) syntax."""
        return self.forward(x)


class BatchNorm2d:
    """Compute batch normalization for 2D spatial inputs"""

    def __init__(self, num_features, eps=1e-5, momentum=0.1):
        """Initialize BatchNorm layer."""
        self.num_features = num_features
        self.eps = eps
        self.momentum = momentum

        # Learnable parameters (requires_grad=True for training)
        # gamma (scale): initialized to 1 so output = normalized input initially
        self.gamma = Tensor(np.ones(self.num_features), requires_grad=True)
        # beta (shift): initialized to 0 so no shift initially
        self.beta = Tensor(np.zeros(self.num_features), requires_grad=True)

        # Running statistics (not trained, accumulated during training)
        # These are used during evaluation for consistent normalization
        self.running_mean = np.zeros(num_features)
        self.running_var = np.ones(num_features)

        # Training mode flag
        self.training = True

    def train(self):
        """Set layer to training mode."""
        self.training = True
        return self

    def eval(self):
        """Set layer to evaluation mode"""
        self.training = False
        return self

    def _validate_input(self, x):

        if len(x.shape) != 4:
            if len(x.shape) == 3:
                raise ValueError(
                    f"BatchNorm2d expected 4D input (batch, channels, height, width), got 3D: {x.shape}\n"
                    f"   Missing batch dimension\n"
                    f"   BatchNorm2d computes statistics over the batch dimension\n"
                    f"   Add batch dim: x.reshape(1, {x.shape[0]}, {x.shape[1]}, {x.shape[2]})"
                )
            elif len(x.shape) == 2:
                raise ValueError(
                    f"BatchNorm2d expected 4D input (batch, channels, height, width), got 2D: {x.shape}\n"
                    f"   Got a matrix, expected an image tensor\n"
                    f"   BatchNorm2d normalizes over spatial dimensions per channel\n"
                    f"   If this is a flattened image, reshape it: x.reshape(1, channels, height, width)"
                )
            else:
                raise ValueError(
                    f"BatchNorm2d expected 4D input (batch, channels, height, width), got {len(x.shape)}D: {x.shape}\n"
                    f"   Wrong number of dimensions\n"
                    f"   BatchNorm2d expects: (batch_size, channels, height, width)\n"
                    f"   Reshape your input to 4D with the correct dimensions"
                )

        batch_size, channels, height, width = x.shape

        if channels != self.num_features:
            raise ValueError(
                f"BatchNorm2d channel mismatch: expected {self.num_features} channels, got {channels}\n"
                f"   Input has {channels} channels but BatchNorm2d was created for {self.num_features}\n"
                f"   BatchNorm2d(num_features) must match the channel dimension of your input\n"
                f"   Either fix your input shape or create BatchNorm2d({channels})"
            )

    def _get_stats(self, x):
        """Get nean and variance for normalization (Batch or running stats)"""

        if self.training:
            # Compute batch statistics per channel
            # Mean over batch and spatial dimensions: axes (0, 2, 3)
            batch_mean = np.mean(x.data, axis=(0, 2, 3))  # Shape: (C,)
            batch_var = np.var(x.data, axis=(0, 2, 3))  # Shape: (C,)

            # Update running statistics (exponential moving average)
            self.running_mean = (
                1 - self.momentum
            ) * self.running_mean + self.momentum * batch_mean
            self.running_var = (
                1 - self.momentum
            ) * self.running_var + self.momentum * batch_var

            return batch_mean, batch_var
        else:
            # Use running statistics (frozen during eval)
            return self.running_mean, self.running_var

    def forward(self, x):
        """
        Forward pass through BatchNorm2d.
        """

        self._validate_input(x)

        batch_size, channels, height, width = x.shape
        mean, var = self._get_stats(x)

        # Normalize: (x - mean) / sqrt(var + eps)
        # Reshape mean and var for broadcasting: (C,) -> (1, C, 1, 1)
        mean_reshaped = mean.reshape(1, channels, 1, 1)
        var_reshaped = var.reshape(1, channels, 1, 1)

        x_normalized = (x.data - mean_reshaped) / np.sqrt(var_reshaped + self.eps)

        # Apply scale (gamma) and shift (beta)
        gamma_reshaped = self.gamma.data.reshape(1, channels, 1, 1)
        beta_reshaped = self.beta.data.reshape(1, channels, 1, 1)

        output = gamma_reshaped * x_normalized + beta_reshaped

        # Return Tensor with gradient tracking
        result = Tensor(
            output, requires_grad=x.requires_grad or self.gamma.requires_grad
        )

        return result

    def parameters(self):
        """Return learnable parameters (gamma and beta)."""
        return [self.gamma, self.beta]

    def __call__(self, x):
        """Enable model(x) syntax."""
        return self.forward(x)


class SimpleCNN:
    """
    Simple CNN demonstrating spatial operations integration
    """

    def __init__(self, num_classes=10):
        """Initialization of Simple CNN"""

        self.conv1 = Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
        self.pool1 = MaxPool2d(kernel_size=2, stride=2)

        self.conv2 = Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
        self.pool2 = MaxPool2d(kernel_size=2, stride=2)

        # Final: 32 channels × 8×8 = 2048 features
        self.flattened_size = 32 * 8 * 8

        self.num_classes = num_classes
        # self.fc = Linear(self.flattened_size, self.num_classes)

    def forward(self, x):
        """Forward pass through Simple CNN"""

        # First conv block
        x = self.conv1(x)
        x = ReLU()(x)  # ReLU activation
        x = self.pool1(x)

        # Second conv block
        x = self.conv2(x)
        x = ReLU()(x)  # ReLU activation
        x = self.pool2(x)

        # Flatten for classification (reshape to 2D)
        batch_size = x.shape[0]
        x = x.reshape(batch_size, -1)
        # x = self.fc(x)
        # Return flattened features
        # In a complete implementation, this would go through a Linear layer
        return x

    def parameters(self):
        """Return all trainable parameters."""
        params = []
        params.extend(self.conv1.parameters())
        params.extend(self.conv2.parameters())
        # params.extend(self.fc.parameters())
        # Linear layer parameters would be added here
        return params

    def __call__(self, x):
        """Enable model(x) syntax."""
        return self.forward(x)
